dataset:
  path: data/dataset_v1.csv
  target: MedHouseVal
  test_size: 0.2
  random_state: 42

preprocess:
  impute_strategy: median
  scale_numeric: true

training:
  cv_folds: 5
  scoring: neg_root_mean_squared_error

models:
  - name: LinearRegression
    estimator: linear_model.LinearRegression
    params: {}

  - name: RandomForest
    estimator: ensemble.RandomForestRegressor
    params:
      n_estimators: [100, 300]
      max_depth: [null, 10, 20]
      min_samples_split: [2, 5]

  - name: GradientBoosting
    estimator: ensemble.GradientBoostingRegressor
    params:
      n_estimators: [100, 300]
      learning_rate: [0.05, 0.1]
      max_depth: [2, 3]
